# Doc site [title, and start page]
site:
  title: Ressources Formateur
  # the 404 page and sitemap files only get generated when the url property is set
  start_page: ressourcesFormateurs::index
  # url gitlab group : 'tebim' + 'formateurs' repo
  #url: https://tebim.gitlab.io/formateurs
  url: https://oturlier.github.io/formateur/
  robots: allow
  #keys:
  #  google_analytics: 'UA-159951047-1'

content:
  sources:
  # Uncomment to build from your local git clone
  - url: .
      # To build locally ensure you have your current local branch listed.
    branches:
    - 'master'
# Uncomment to build from the remote github repository.
  #- https://github.com/oturlier/ressources-formateurs.git
    
ui:
  bundle:
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
    url: ./ui/build/ui-bundle.zip
    # for lunr search
  #supplemental_files: ./supplemental_ui
  #supplemental_files: ./branding/supplemental-ui/uyuni/uyuni-webui

asciidoc:
  attributes:
    doctype: book
    # Asciidoc Configuration Attributes
    linkattrs: 
    sectlinks: true
    icons: font
    experimental: true
    lang: fr
    plantuml-server-url: 'http://www.plantuml.com/plantuml'
    plantuml-fetch-diagram: true
    toc-title: Sommaire
    warning-caption: Attention
    tip-caption: Conseil
    note-caption: Info
    authors: Team formateurs TEB
    _editors: CRM Mulhouse
    _contributors: Formateurs autres
    _proofreaders: Marc ARMSPACH
    _participants:
    _summary: Ce manuel montre les outils et les méthodes employées pour contribuer aux ressources formatives TEB
    keywords: CRM, TEB, Ressources, édition, publication, asciidoc, antora
    _dochistory: édition initiale
    _citation: '{authors},{docyear},{doctitle}'
    _copyleft: CRM Mulhouse et auteurs de ce texte
    _license_1: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC-BY-NC-SA-4.0)
    _license_2: GNU Free Documentation (GFDL-1.3-or-later)
    # Included products and versions
    productname: 'Manuel Formateurs TEB'
    productnumber: 2020
    docversion: '1.0'
    minorversion: '1.0.1'
    # substitution words
    loo: LibreOffice
    asc: Asciidoc
    pdoc: Pandoc
    uri_pdoc: https://pandoc.org/index.html
    word: Microsoft Word
    htm: HTML
    dblcdr: Double Commander
    notpad: Notepad{plus}{plus}
    pwrshl: Powershell 7
    win: Windows
    MS: Microsoft Windows
    imagik: Imagemagick
    y: icon:check[role="green"]
    n: icon:times[role="red"]
    c: icon:file-text-o[role="blue"]
    subl: Sublime Text
    vscode: Visual Studio Code

  extensions:
  - asciidoctor-plantuml
  - ./lib/extensions/json-config-ui-block-macro.js
  - ./lib/extensions/inline-man-macro.js
  - ./lib/extensions/multirow-table-head-tree-processor.js
  - ./lib/extensions/swagger-ui-block-macro.js
  - ./lib/extensions/tabs-block.js


output:
  # for gitlab pages
  #dir: ./public
  # for github pages
  dir: ./docs
runtime:
  cache_dir: ./.cache/antora
  fetch: true
