[#guide-diagrammes]
= Diagrammes


== Diagrammes

[cols=3]
|===
|a
|b
|c

|1
|2
|3
|===


//// 
=== Gnuplot

//Failed to generate image: No such file or directory - C:\Program Files\gnuplot\bin/gnuplot.EXE
// but C:\Program Files\gnuplot\bin\gnuplot.exe exists!
// linux : no problemo!
[gnuplot,gnuplot1,svg]
....
plot sin(x)
.... 
////


=== ditaa

And here goes a diagram

.ditaa!
[ditaa, ditaa, svg]
....
                   +-------------+
                   | Asciidoctor +-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        +---+ Asciidoctor +--->|               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....



=== UML Sequence diagram

.sequence
[plantuml, rma-sequence-diagram, svg]
....
participant User
User -> A: DoWork
activate A
A -> B: << createRequest >>
activate B
B -> C: DoWork
activate C
C --> B: WorkDone
destroy C
B --> A: RequestCreated
deactivate B
A -> User: Done
deactivate A
....

=== Use case diagram

.use case
[plantuml, rma-use-case-diagram, svg]
....
left to right direction

actor developer
database repo as "central\nrepo"
agent jenkins as "Jenkins"

rectangle admin as "Gerrit / Gitlab" {
    agent ui as "front"
    database repo_local as "local\nrepo"
}

developer --> ui : push
ui --> repo_local : push
ui -left-> jenkins: "\npush "
ui ..> repo : replication
....

=== Class diagram

.classes
[plantuml, rma-class-diagram, svg]
....
abstract class ArrayList {
  Object[] elementData
  size()
}
enum TimeUnit {
  DAYS
  HOURS
  MINUTES
}
Interface BaseClass

namespace net.dummy {
    .BaseClass <|-- Person
    Meeting o-- Person

    .BaseClass <|- Meeting
}
namespace net.foo {
  net.dummy.Person  <|- Person
  .BaseClass <|-- Person

  net.dummy.Meeting o-- Person
}
BaseClass <|-- net.unused.Person
....


.Relations?
[plantuml, bob, png]
----
alice -> bob
bob -> alice
----




.classes, encore
[plantuml, diagram-classes, png]
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....



=== Activity diagram

.activity
[plantuml, activity-diagram, svg]
....
(*) --> "Initialization"

if "Some Test" then
  -->[true] "Some Activity"
  --> "Another activity"
  -right-> (*)
else
  ->[false] "Something else"
  -->[Ending process] (*)
endif
....



=== icon:crutch[] Another activity diagram


.Process
[plantuml, cv-generation, svg]
....
@startuml
skinparam monochrome true
|local (git)|
start
:modify laTeX file;
:commit changes;
:run <i>Makefile;
:commit updated PDF;
:push changes;
|Build pipeline|
:generate static web page
treating CV (PDF) as an artifact;
:upload static web page;
|Web server|
:provide web page;
|Viewer|
:enjoy my CV;
stop
@enduml
....


=== e

// #skinparam monochrome false #true
.Worflow édition
[plantuml, edition1, svg]
....
@startuml
|#dee4e8|Auteur (interne)|
start
:édite document;
:envoie au **Vérificateur**>
|#c4c9cd|Vérificateur (interne)|
:vérifie **le fond** du document;
if (OK) then 
  :envoie au **Contrôleur**>
  else
  :formule des remarques à l'auteur;
|Auteur (interne)|
:modifie doc;
:envoie au **Vérificateur**>
endif
|Vérificateur (interne)|
:valide les modifications
effectuées suite à
ses remarques;
|#daf0fe|Contrôleur (interne)|
:vérifie **la forme** du document;
:formule des remarques
à l'auteur;
:valide les modifications
effectuées suite à
ses remarques;
|Client (externe)|
:reçoit le document
vérifié (fond & forme);
:formule des remarques
à l'auteur;
:valide les modifications
effectuées suite à
ses remarques;
stop
@enduml
....

=== r


.process21
[plantuml, process21, svg]
....
@startuml
(*) --> "Initialization"

if "Some Test" then
  -->[true] "Some Activity"
  --> "Another activity"
  -right-> (*)
else
  ->[false] "Something else"
  -->[Ending process] (*)
endif
@enduml
....

=== tu

.process31
[plantuml, process31, svg]
....
@startuml
partition Conductor {
  (*) --> "Climbs on Platform"
  --> === S1 ===
  --> Bows
}

partition Audience #LightSkyBlue {
  === S1 === --> Applauds
}

partition Conductor {
  Bows --> === S2 ===
  --> WavesArmes
  Applauds --> === S2 ===
}

partition Orchestra #CCCCEE {
  WavesArmes --> Introduction
  --> "Play music"
}
@enduml
....




=== ho

.process8
[plantuml, process8, svg]
....
@startuml
actor Bob #red
' The only difference between actor
'and participant is the drawing
participant Alice
participant "I have a really\nlong name" as L #99FF99
/' You can also declare:
participant L as "I have a really\nlong name" #99FF99
'/
Alice ->Bob: Authentication Request
Bob->Alice: Authentication Response
Bob->L: Log transaction
@enduml
....

=== ji

.process1
[plantuml, process1, svg]
....
@startuml
Bob -[#red]> Alice : hello
Alice -[#0000FF]->Bob : ok
@enduml
....



=== lif


.Worflow édition78
[plantuml, edition78, svg]
....
@startuml
scale 1.5
== document état PREL ==
Auteur -> Vérificateur: envoi pour vérification **fond**
Vérificateur --> Auteur: émission remarques
Auteur -> Vérificateur: renvoi modifications
Vérificateur --> Auteur: avis OK
Auteur -> Contrôleur: envoi pour vérification **forme**
Contrôleur --> Auteur: émission remarques
Auteur -> Contrôleur: renvoi modifications
Contrôleur --> Auteur: avis OK
Auteur -> Client: envoi version **PREL** pour avis
Client --> Auteur: émission remarques
Auteur -> Client: renvoi modifications
Client --> Auteur: avis OK
== document état BPE ==
Auteur -> Client: renvoi version **BPE** pour utilisation
@enduml
....

=== maa

.Worflow3
[plantuml, workflow3, svg]
....
@startuml
scale 1.5
start
:édition;
:envoi;
fork
:Vérificateur;
fork again
:Contrôleur;
end fork
while (OK) is (NOK)
:modifications;
endwhile
fork
:envoi client;
while (OK) is (NOK)
:modifications;
endwhile
:renvoi;
end fork
stop
@enduml
....





=== icon:poop[] Let's go wide icon:bicycle[]?

.wide relatons
[plantuml]
....
@startuml

skinparam activity {
  BackgroundColor<< Paks >> Yellow
  BackgroundColor<< Bins >> Green
  BackgroundColor<< Package >> Cyan
  BackgroundColor<< Linux >> Brown
}

(*) --> ===B1===
===B1=== --> "Cook Paks" << Paks >>
===B1=== --> "PS4 Profile Bins" << Bins >>
===B1=== --> "PS4 Release Bins" << Bins >>
===B1=== --> "XBox Profile Bins" << Bins >>
===B1=== --> "XBox Release Bins" << Bins >>
===B1=== --> "x64 Bins" << Bins >>
===B1=== --> "Switch Bins" << Bins >>
===B1=== --> "Tests"
===B1=== --> "Data Checks"
"Cook Paks" --> "PS4 Profile Package" << Package >>
"Cook Paks" --> "PS4 Release Package" << Package >>
"Cook Paks" --> "XBox Profile Package" << Package >>
"Cook Paks" --> "XBox Release Package" << Package >>
"Cook Paks" --> "Linux" << Linux >>
"PS4 Profile Bins" --> "PS4 Profile Package" << Package >>
"PS4 Release Bins" --> "PS4 Release Package" << Package >>
"XBox Profile Bins" --> "XBox Profile Package" << Package >>
"XBox Release Bins" --> "XBox Release Package" << Package >>
"PS4 Profile Package" --> ===B2===
"PS4 Release Package" --> ===B2===
"XBox Profile Package" --> ===B2===
"XBox Release Package" --> ===B2===
"Linux" --> ===B2===
"Tests" --> ===B2===
"Data Checks" --> ===B2===
"x64 Bins" --> ===B2===
"Switch Bins" --> ===B2===
===B2=== --> (*)
@enduml
....


=== Component diagram

.components
[plantuml, rma-component-diagram, svg]
....
package "Some Group" {
  HTTP - [First Component]
  [Another Component]
}
rectangle "Other Groups" {
  FTP - [Second Component]
  [First Component] --> FTP
}
cloud {
  [Example 1]
}
database "MySql" {
  folder "This is my folder" {
    [Folder 3]
  }
  frame "Foo" {
    [Frame 4]
  }
}
[Another Component] --> [Example 1]
[Example 1] -right-> [Folder 3]
[Folder 3] --> [Frame 4]
....

=== State diagram

.state
[plantuml, rma-state-diagram, svg]
....
[*] -left-> State1
State1 -left-> State2 : Succeeded
State1 --> [*] : Aborted
State2 --> State3 : Succeeded
State2 --> [*] : Aborted
state State3 {
  state "Accumulate Enough Data\nLong State Name" as long1
  long1 : Just a test
  [*] --> long1
  long1 --> long1 : New Data
  long1 --> ProcessData : Enough Data
}
State3 --> State3 : Failed
State3 --> [*] : Succeeded
State3 --> [*] : Aborted
....

=== Work Breakdown Structure

.wbs
[plantuml, wbs, svg]
....
@startwbs
* Business Process Modelling WBS
** Launch the project
*** Stakeholder Research
*** Implementation Plan
** Design phase
*** AsIs Processes Completed
****< AsIs Processes Completed1
****> AsIs Processes Completed2
***< AsIs performance metrics
***< Identify Quick Wins
@endwbs
....

=== Timing diagram

.time
[plantuml, timing, svg]
....
'skinparam backgroundColor white # does not work
robust "Web Browser" as WB
concise "Web User" as WU
WB is Initializing
WU is Absent
@WB
0 is idle
+200 is Processing
+100 is Waiting
WB@0 <-> @50 : {50 ms lag}
@WU
WU -> WB : URL
0 is Waiting #white
+500 is ok #white
@200 <-> @+150 : {150 ms}
....





.time6
[plantuml, timing6, svg]
....
@startuml
robust "Web Browser" as WB
concise "Web User" as WU

@2019/07/02
WU is Idle
WB is Idle

@2019/07/04
WU is Waiting : some note
WB is Processing : some other note

@2019/07/05
WB is Waiting
@enduml
....


=== Mind Map

.mind
[plantuml, mindmap, svg]
....
@startmindmap
* Debian
** Ubuntu
*** Linux Mint
*** Kubuntu
*** Lubuntu
*** KDE Neon
** LMDE
** SolydXK
** SteamOS
** Raspbian with a very long name
*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio
@endmindmap
....

=== Gantt diagram

.gantt
[plantuml, gantt01, svg]
....
@startgantt
[Test prototype] lasts 10 days
[Prototype completed] happens at [Test prototype]'s end
[Setup assembly line] lasts 12 days
[Setup assembly line] starts at [Test prototype]'s end
@endgantt
....



.gantt2
[plantuml, gantt2, svg]
....
@startgantt
[Design du prototype] lasts 13 days and is colored in Lavender/LightBlue
[Test du prototype] lasts 9 days and is colored in Coral/Green and starts 3 days after [Design du prototype]'s end
[Écriture des tests] lasts 5 days and ends at [Design du prototype]'s end
[Embauche des rédacteurs] lasts 6 days and ends at [Écriture des tests]'s start
[Écriture des rapports] is colored in Coral/Green
[Écriture des rapports] starts 1 day before [Test du prototype]'s start and ends at [Test du prototype]'s end
@endgantt
....

.gantt3
[plantuml, gantt3, svg]
....
@startgantt
scale 1.5
[Task1] lasts 10 days
then [Task2] lasts 4 days
-- Phase Two --
then [Task3] lasts 5 days
then [Task4] lasts 6 days
@endgantt
....

// .gantt4
// [plantuml, gantt4, svg]
// ....
// @startgantt
// [Prototype design] lasts 14 days
// [Build prototype] lasts 4 days
// [Prepare test] lasts 6 days
// [Prototype design] -> [Build prototype]
// [Prototype design] -> [Prepare test]
// @endgantt
// ....



.gantt5
[plantuml, gantt5, svg]
....
@startgantt
printscale daily
Project starts the 16th of mars 2020
saturday are closed
sunday are closed
[Test du prototype] lasts 18 days and is 100% completed
[Prototype terminé] happens at [Test du prototype]'s end
[Mise en place production] lasts 19 days and is 30% completed
[Mise en place production] starts at [Test du prototype]'s end
@endgantt
....




== Chimie

.chem
stem:[\ce{H_2O}]


== Maths

=== Inline equations

Inline equation: stem:[e^{ i \theta_1} = \cos{\theta_1} + i \sin{\theta_1}]

Block equation:

.equ1
[stem]
++++
\frac{\partial^2 u}{\partial x^2} = \frac{1}{c^2} \frac{\partial^2 u}{\partial t^2}
++++

=== Equations in normal blocks

.equ2
[latexmath]
++++
k_{n+1} = n^2 + k_n^2 - k_{n-1}
++++

Some useful text! Formula for quadratic root:

.equ3
[stem]
++++
x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
++++

Inline equation works too! latexmath:[a^2+b^2=c^2]. Or as stem
stem:[a^2+b^2=c^2]. Pretty nice, huh?