[#guide-diagrammes]
= Diagrammes


== Diagrammes

[cols=3]
|===
|a
|b
|c

|1
|2
|3
|===


//// 
=== Gnuplot

//Failed to generate image: No such file or directory - C:\Program Files\gnuplot\bin/gnuplot.EXE
// but C:\Program Files\gnuplot\bin\gnuplot.exe exists!
// linux : no problemo!
[gnuplot,gnuplot1,svg]
....
plot sin(x)
.... 
////


=== ditaa

And here goes a diagram

.ditaa!
[ditaa, ditaa, svg]
....
                   +-------------+
                   | Asciidoctor +-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        +---+ Asciidoctor +--->|               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....



=== UML Sequence diagram

.sequence
[plantuml, rma-sequence-diagram, svg]
....
participant User
User -> A: DoWork
activate A
A -> B: << createRequest >>
activate B
B -> C: DoWork
activate C
C --> B: WorkDone
destroy C
B --> A: RequestCreated
deactivate B
A -> User: Done
deactivate A
....

=== Use case diagram

.use case
[plantuml, rma-use-case-diagram, svg]
....
left to right direction

actor developer
database repo as "central\nrepo"
agent jenkins as "Jenkins"

rectangle admin as "Gerrit / Gitlab" {
    agent ui as "front"
    database repo_local as "local\nrepo"
}

developer --> ui : push
ui --> repo_local : push
ui -left-> jenkins: "\npush "
ui ..> repo : replication
....

=== Class diagram

.classes
[plantuml, rma-class-diagram, svg]
....
abstract class ArrayList {
  Object[] elementData
  size()
}
enum TimeUnit {
  DAYS
  HOURS
  MINUTES
}
Interface BaseClass

namespace net.dummy {
    .BaseClass <|-- Person
    Meeting o-- Person

    .BaseClass <|- Meeting
}
namespace net.foo {
  net.dummy.Person  <|- Person
  .BaseClass <|-- Person

  net.dummy.Meeting o-- Person
}
BaseClass <|-- net.unused.Person
....


.Relations?
[plantuml, bob, png]
----
alice -> bob
bob -> alice
----



.classes, encore
[plantuml, diagram-classes, png]
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....



=== Activity diagram

.activity
[plantuml, activity-diagram, svg]
....
(*) --> "Initialization"

if "Some Test" then
  -->[true] "Some Activity"
  --> "Another activity"
  -right-> (*)
else
  ->[false] "Something else"
  -->[Ending process] (*)
endif
....



=== icon:crutch[] Another activity diagram


.Process
[plantuml, cv-generation, svg]
....
@startuml
skinparam monochrrome true
|local (git)|
start
:modify laTeX file;
:commit changes;
:run <i>Makefile;
:commit updated PDF;
:push changes;
|Build pipeline|
:generate static web page
treating CV (PDF) as an artifact;
:upload static web page;
|Web server|
:provide web page;
|Viewer|
:enjoy my CV;
stop
@enduml
....


=== icon:poop[] Let's go wide icon:bicycle[]?

.wide relatons
[plantuml]
....
@startuml

skinparam activity {
  BackgroundColor<< Paks >> Yellow
  BackgroundColor<< Bins >> Green
  BackgroundColor<< Package >> Cyan
  BackgroundColor<< Linux >> Brown
}

(*) --> ===B1===
===B1=== --> "Cook Paks" << Paks >>
===B1=== --> "PS4 Profile Bins" << Bins >>
===B1=== --> "PS4 Release Bins" << Bins >>
===B1=== --> "XBox Profile Bins" << Bins >>
===B1=== --> "XBox Release Bins" << Bins >>
===B1=== --> "x64 Bins" << Bins >>
===B1=== --> "Switch Bins" << Bins >>
===B1=== --> "Tests"
===B1=== --> "Data Checks"
"Cook Paks" --> "PS4 Profile Package" << Package >>
"Cook Paks" --> "PS4 Release Package" << Package >>
"Cook Paks" --> "XBox Profile Package" << Package >>
"Cook Paks" --> "XBox Release Package" << Package >>
"Cook Paks" --> "Linux" << Linux >>
"PS4 Profile Bins" --> "PS4 Profile Package" << Package >>
"PS4 Release Bins" --> "PS4 Release Package" << Package >>
"XBox Profile Bins" --> "XBox Profile Package" << Package >>
"XBox Release Bins" --> "XBox Release Package" << Package >>
"PS4 Profile Package" --> ===B2===
"PS4 Release Package" --> ===B2===
"XBox Profile Package" --> ===B2===
"XBox Release Package" --> ===B2===
"Linux" --> ===B2===
"Tests" --> ===B2===
"Data Checks" --> ===B2===
"x64 Bins" --> ===B2===
"Switch Bins" --> ===B2===
===B2=== --> (*)

@enduml
....

=== Component diagram

.components
[plantuml, rma-component-diagram, svg]
....
package "Some Group" {
  HTTP - [First Component]
  [Another Component]
}
rectangle "Other Groups" {
  FTP - [Second Component]
  [First Component] --> FTP
}
cloud {
  [Example 1]
}
database "MySql" {
  folder "This is my folder" {
    [Folder 3]
  }
  frame "Foo" {
    [Frame 4]
  }
}
[Another Component] --> [Example 1]
[Example 1] -right-> [Folder 3]
[Folder 3] --> [Frame 4]
....

=== State diagram

.state
[plantuml, rma-state-diagram, svg]
....
[*] -left-> State1
State1 -left-> State2 : Succeeded
State1 --> [*] : Aborted
State2 --> State3 : Succeeded
State2 --> [*] : Aborted
state State3 {
  state "Accumulate Enough Data\nLong State Name" as long1
  long1 : Just a test
  [*] --> long1
  long1 --> long1 : New Data
  long1 --> ProcessData : Enough Data
}
State3 --> State3 : Failed
State3 --> [*] : Succeeded
State3 --> [*] : Aborted
....

=== Work Breakdown Structure

.wbs
[plantuml, wbs, svg]
....
@startwbs
* Business Process Modelling WBS
** Launch the project
*** Stakeholder Research
*** Implementation Plan
** Design phase
*** AsIs Processes Completed
****< AsIs Processes Completed1
****> AsIs Processes Completed2
***< AsIs performance metrics
***< Identify Quick Wins
@endwbs
....

=== Timing diagram

.time
[plantuml, timing, svg]
....
'skinparam backgroundColor white # does not work
robust "Web Browser" as WB
concise "Web User" as WU
WB is Initializing
WU is Absent
@WB
0 is idle
+200 is Processing
+100 is Waiting
WB@0 <-> @50 : {50 ms lag}
@WU
WU -> WB : URL
0 is Waiting #white
+500 is ok #white
@200 <-> @+150 : {150 ms}
....

=== Mind Map

.mind
[plantuml, mindmap, svg]
....
@startmindmap
* Debian
** Ubuntu
*** Linux Mint
*** Kubuntu
*** Lubuntu
*** KDE Neon
** LMDE
** SolydXK
** SteamOS
** Raspbian with a very long name
*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio
@endmindmap
....

=== Gantt diagram

.gantt
[plantuml, gantt, svg]
....
@startgantt
[Test prototype] lasts 10 days
[Prototype completed] happens at [Test prototype]'s end
[Setup assembly line] lasts 12 days
[Setup assembly line] starts at [Test prototype]'s end
@endgantt
....

== Chimie

.chem
stem:[\ce{H_2O}]


== Maths

=== Inline equations

Inline equation: stem:[e^{ i \theta_1} = \cos{\theta_1} + i \sin{\theta_1}]

Block equation:

.equ1
[stem]
++++
\frac{\partial^2 u}{\partial x^2} = \frac{1}{c^2} \frac{\partial^2 u}{\partial t^2}
++++

=== Equations in normal blocks

.equ2
[latexmath]
++++
k_{n+1} = n^2 + k_n^2 - k_{n-1}
++++

Some useful text! Formula for quadratic root:

.equ3
[stem]
++++
x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
++++

Inline equation works too! latexmath:[a^2+b^2=c^2]. Or as stem
stem:[a^2+b^2=c^2]. Pretty nice, huh?